/**
 * Created by vedi on 07/04/2017.
 */

const resourceMap = {
    bodyPartBar: 'bodyPartBar.svg',
    circle: 'circle.svg',
    constructedWall: 'constructedWall.svg',
    controller: 'controller.svg',
    'controller-level': 'controller-level.svg',
    cover: 'cover.svg',
    'creep-npc': 'creep-npc.svg',
    'creep-mask': 'creep-mask.png',
    flag: 'flag.svg',
    'flag-secondary': 'flag-secondary.svg',
    extension: 'extension.svg',
    'extension-border50': 'extension-border50.svg',
    'extension-border100': 'extension-border100.svg',
    'extension-border200': 'extension-border200.svg',
    extractor: 'extractor.svg',
    'exit-left': 'exit-left.svg',
    'exit-top': 'exit-top.svg',
    'exit-bottom': 'exit-bottom.svg',
    'exit-right': 'exit-right.svg',
    flare1: 'flare1.png',
    flare2: 'flare2.png',
    glow: 'glow.png',
    lab: 'lab.svg',
    'lab-highlight': 'lab-highlight.svg',
    'lab-mineral': 'lab-mineral.svg',
    link: 'link.svg',
    'link-energy': 'link-energy.svg',
    'link-border': 'link-border.svg',
    nuke: 'nuke.svg',
    nuker: 'nuker.svg',
    'nuker-border': 'nuker-border.svg',
    powerBank: 'powerBank.svg',
    rectangle: 'rectangle.svg',
    rampart: 'rampart.svg',
    storage: 'storage.svg',
    'storage-border': 'storage-border.svg',
    tbd: 'tbd.svg',
    terminal: 'terminal.svg',
    'terminal-border': 'terminal-border.svg',
    'terminal-highlight': 'terminal-highlight.svg',
    'terminal-arrows': 'terminal-arrows.svg',
    'tombstone-border': 'tombstone-border.svg',
    'tombstone-resource': 'tombstone-resource.svg',
    tough: 'tough.svg',
    'tower-base': 'tower-base.svg',
    'tower-rotatable': 'tower-rotatable.svg',
    ground: 'ground.png',
    'ground-mask': 'ground-mask.png',
    'ground-mask2': 'ground-mask2.png',
    noise1: 'noise1.png',
    noise2: 'noise2.png',
};

const rescaleResources = [
    'creep-npc',
    'flag',
    'flag-secondary',
    'powerBank',
    'extractor',
    'controller',
    'controller-level',
    'constructedWall',
    'nuker',
    'nuker-border',
    'link',
    'link-border',
    'extension-border50',
    'extension-border100',
    'extension-border200',
    'lab',
    'terminal-border',
    'terminal-arrows',
    'bodyPartBar',
    'tower-base',
    'storage',
    'storage-border',
    'tombstone-border',
    'tombstone-resource'
];

export { resourceMap, rescaleResources };