/**
 * Created by vedi on 07/04/2017.
 */

const resourceMap = {
    berserk: 'berserk.svg',
    bodyPartBar: 'bodyPartBar.svg',
    circle: 'circle.svg',
    commander: 'commander.svg',
    'commander-lvl1': 'commander-lvl1.svg',
    'commander-lvl2': 'commander-lvl2.svg',
    'commander-lvl3': 'commander-lvl3.svg',
    'commander-lvl4': 'commander-lvl4.svg',
    constructedWall: 'constructedWall.svg',
    controller: 'controller.svg',
    'controller-level': 'controller-level.svg',
    'corrupt-source': 'corrupt-source.svg',
    cover: 'cover.svg',
    'creep-npc': 'creep-npc.svg',
    'creep-mask': 'creep-mask.png',
    defend: 'defend.svg',
    demolish: 'demolish.svg',
    disable: 'disable.svg',
    'disable-spawn': 'disable-spawn.svg',
    'disable-tower': 'disable-tower.svg',
    'drain-extension': 'drain-extension.svg',
    encourage: 'encourage.svg',
    exhaust: 'exhaust.svg',
    'extend-mineral': 'extend-mineral.svg',
    'extend-source': 'extend-source.svg',
    flag: 'flag.svg',
    'flag-secondary': 'flag-secondary.svg',
    executor: 'executor.svg',
    'executor-lvl1': 'executor-lvl1.svg',
    'executor-lvl2': 'executor-lvl2.svg',
    'executor-lvl3': 'executor-lvl3.svg',
    'executor-lvl4': 'executor-lvl4.svg',
    extension: 'extension.svg',
    'extension-border50': 'extension-border50.svg',
    'extension-border100': 'extension-border100.svg',
    'extension-border200': 'extension-border200.svg',
    extractor: 'extractor.svg',
    'exit-left': 'exit-left.svg',
    'exit-top': 'exit-top.svg',
    'exit-bottom': 'exit-bottom.svg',
    'exit-right': 'exit-right.svg',
    flare1: 'flare1.png',
    flare2: 'flare2.png',
    'harvest-energy': 'harvest-energy.svg',
    'harvest-mineral': 'harvest-mineral.svg',
    'generate-ops': 'generate-ops.svg',
    glow: 'glow.png',
    ground: 'ground.png',
    'ground-mask': 'ground-mask.png',
    'ground-mask2': 'ground-mask2.png',
    kill: 'kill.svg',
    lab: 'lab.svg',
    'lab-highlight': 'lab-highlight.svg',
    'lab-mineral': 'lab-mineral.svg',
    link: 'link.svg',
    'link-energy': 'link-energy.svg',
    'link-border': 'link-border.svg',
    'mass-repair': 'mass-repair.svg',
    noise1: 'noise1.png',
    noise2: 'noise2.png',
    nuke: 'nuke.svg',
    nuker: 'nuker.svg',
    'nuker-border': 'nuker-border.svg',
    'operate-extension': 'operate-extension.svg',
    'operate-lab': 'operate-lab.svg',
    'operate-observer': 'operate-observer.svg',
    'operate-spawn': 'operate-spawn.svg',
    'operate-storage': 'operate-storage.svg',
    'operate-terminal': 'operate-terminal.svg',
    'operate-tower': 'operate-tower.svg',
    operator: 'operator.svg',
    'operator-lvl1': 'operator-lvl1.svg',
    'operator-lvl2': 'operator-lvl2.svg',
    'operator-lvl3': 'operator-lvl3.svg',
    'operator-lvl4': 'operator-lvl4.svg',
    powerBank: 'powerBank.svg',
    punch: 'punch.svg',
    rampart: 'rampart.svg',
    rectangle: 'rectangle.svg',
    reflect: 'reflect.svg',
    reinforce: 'reinforce.svg',
    'remote-transfer': 'remote-transfer.svg',
    renew: 'renew.svg',
    shield: 'shield.svg',
    sight: 'sight.svg',
    snipe: 'snipe.svg',
    storage: 'storage.svg',
    'storage-border': 'storage-border.svg',
    summon: 'summon.svg',
    tbd: 'tbd.svg',
    terminal: 'terminal.svg',
    'terminal-border': 'terminal-border.svg',
    'terminal-highlight': 'terminal-highlight.svg',
    'terminal-arrows': 'terminal-arrows.svg',
    'tombstone-border': 'tombstone-border.svg',
    'tombstone-resource': 'tombstone-resource.svg',
    tough: 'tough.svg',
    'tower-base': 'tower-base.svg',
    'tower-rotatable': 'tower-rotatable.svg',
};

const rescaleResources = [
    'bodyPartBar',
    'controller',
    'controller-level',
    'constructedWall',
    'creep-npc',
    'extension-border50',
    'extension-border100',
    'extension-border200',
    'extractor',
    'flag',
    'flag-secondary',
    'lab',
    'link',
    'link-border',
    'nuker',
    'nuker-border',
    'powerBank',
    'storage',
    'storage-border',
    'terminal-border',
    'terminal-arrows',
    'tombstone-border',
    'tombstone-resource',
    'tower-base',
    'commander',
    'commander-lvl1',
    'commander-lvl2',
    'commander-lvl3',
    'commander-lvl4',
    'executor',
    'executor-lvl1',
    'executor-lvl2',
    'executor-lvl3',
    'executor-lvl4',
    'operator',
    'operator-lvl1',
    'operator-lvl2',
    'operator-lvl3',
    'operator-lvl4',
];

export { resourceMap, rescaleResources };
